name: Build and deploy Node.js app to Azure Web App - Saani210042129

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      # Set up Node.js version
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Install backend dependencies (since backend is in the root directory)
      - name: Install backend dependencies
        run: |
          npm install  # Install backend dependencies in the root directory

      # Install frontend dependencies
      - name: Install frontend dependencies
        run: |
          cd auth-frontend
          npm install  # Install frontend dependencies (including react-scripts)

      # Build the React app (Frontend)
      - name: Build React app
        run: |
          cd auth-frontend  # Build React app in the frontend directory
          npm run build

      # Zip the backend and the built frontend together for deployment
      - name: Zip artifact for deployment
        run: |
          zip -r release.zip ./auth-frontend/build ./app.js  # Include the React build folder and the backend (app.js)

      # Upload the artifact for the deployment job
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_243AF42589094A0D9E354F7058B4D0A6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D4DABFD74C534513B4E37CFE4AD48B97 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9DCE20CDD77743C4981A400F73A69C67 }}

      # Deploy to Azure Web App
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Sani210042129'
          slot-name: 'Production'
          package: .  # Deploy the unzipped contents